version: "3.8"

services:
  # Frontend service (Angular + Nginx)
  frontend:
    build:
      context: ./frontend  # Path to the frontend Dockerfile
      dockerfile: Dockerfile  # Explicitly point to the Dockerfile if needed
    image: sanchalkhedkar/frontend:latest  # Image name for frontend
    ports:
      - "8081:80"  # Expose port 80 of the frontend (Nginx) to port 8081 on the host machine
    networks:
      - fullstack-network

  # Backend service (Spring Boot)
  backend:
    build:
      context: ./backend  # Path to the backend Dockerfile
      dockerfile: Dockerfile  # Explicitly point to the Dockerfile if needed
    image: sanchalkhedkar/backend:latest  # Image name for backend
    ports:
      - "8080:8080" 
