version: '3.8'

services:
  frontend: # Changed to lowercase
    build:
      context: ./Frontend
      dockerfile: Dockerfile # Specify the Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend
    restart: unless-stopped # Add a restart policy
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile # Specify the Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped # Add a restart policy
