version: "3.8"

services:
  fullstack-app:
    build:
      context: .  # Path where Dockerfile is located
    image: sanchalkhedkar/fullstack-app:latest
    ports:
      - "8080:8080"  # Spring Boot (backend)
      - "8081:80"    # Nginx (frontend)
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
