version: '3.8'

services:
  fullstack-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: your-dockerhub-username/fullstack-app:latest
    ports:
      - "8080:8080"
      - "80:80"
