version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    image: sanchalkhedkar/frontend   # REQUIRED to push
    ports:
      - "4200:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    image: sanchalkhedkar/backend    # REQUIRED to push
    ports:
      - "8080:8080"
