version: "3.8"

services:
  backend:
    build:
      context: ./backend  # Path to the backend folder
      dockerfile: Dockerfile  # Use the backend Dockerfile
    image: sanchalkhedkar/combined_app_backend:latest  # Tag the backend image
    ports:
      - "8080:8080"  # Expose backend on port 8080
    environment:
      - SPRING_PROFILES_ACTIVE=prod  # Optional: Set Spring profile
    networks:
      - app-network  # Custom network for communication between services

  frontend:
    build:
      context: ./frontend  # Path to the frontend folder
      dockerfile: Dockerfile  # Use the frontend Dockerfile
    image: sanchalkhedkar/combined_app_frontend:latest  # Tag the frontend image
    ports:
      - "80:80"  # Expose frontend on port 80 (served by Nginx)
    networks:
      - app-network  # Custom network for communication with backend (optional)

# Define a custom network to allow frontend and backend to communicate
networks:
  app-network:
    driver: bridge
