version: '3.8'
services:
  backend:
    build:
      context: .  # This should be the directory containing the Dockerfile
      dockerfile: Dockerfile
    # ...
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    # ...
