name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      
    tags:
      - 'v*.*.*'

env:
  DOCKER_REPO: sanchalkhedkar/asas

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: sanchalkhedkar
          password: dckr_pat_yC7BqB9FPf8d_ZT9M_A4dktjrWo

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_REPO }}
          tags: |
            type=semver,pattern=v{{version}},enable=${{ startsWith(github.ref, 'refs/tags/') }}
            type=sha,format=short,enable=${{ startsWith(github.ref, 'refs/heads/') }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Output pushed image info
        run: echo "Image pushed: ${{ steps.meta.outputs.tags }}"
